services:
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    env_file: .env
    networks:
      - traefik-docker-stack_traefik_network
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.redis.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.redis.entrypoints=websecure
      - traefik.http.routers.redis.tls.certresolver=${CERTRESOLVER}
      - io.portainer.accesscontrol.public=true
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data

networks:
  traefik-docker-stack_traefik_network:
    external: true

volumes:
  redis_data:
